# Generated by Django 5.1.4 on 2025-02-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment_payment_link_payment_session_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_link",
            field=models.CharField(
                blank=True, max_length=400, null=True, verbose_name="Id сессии"
            ),
        ),
    ]
