# Generated by Django 5.1.4 on 2025-02-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payment_payment_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Статус транзакции"
            ),
        ),
    ]
