# Generated by Django 5.1.4 on 2025-02-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_alter_subscription_course_alter_subscription_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
