# Generated by Django 5.1.4 on 2025-02-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0006_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
    ]
